// <auto-generated />
namespace SPlus.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_Manager_To_OrgStructure_And_ChangeSO_Owner_To_Optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Manager_To_OrgStructure_And_ChangeSO_Owner_To_Optional));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231046168_Add_Manager_To_OrgStructure_And_ChangeSO_Owner_To_Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
