// <auto-generated />
namespace SPlus.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_TwoFactorTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_TwoFactorTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202405260945356_update_TwoFactorTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
